global
chroot /var/lib/haproxy
daemon
group haproxy
log 10.0.2.1 local0
maxconn 4000
pidfile /var/run/haproxy.pid
stats socket /var/lib/haproxy/stats
user haproxy
defaults
log global
maxconn 8000
option redispatch
retries 3
stats enable
timeout http-request 10s
timeout queue 1m
timeout connect 10s
timeout client 1m
timeout server 1m
timeout check 10s
listen puppet
bind 10.0.2.10:8140
mode tcp
balance source
option ssl-hello-chk
timeout client 1000000
timeout server 1000000
server puppet-master-4.pro-puppet.com puppet-master-4.pro-puppet.com :8140 check
server puppet-master-5.pro-puppet.com puppet-master-5.pro-puppet.com:8140 check
